# Generated by Django 5.0.6 on 2024-05-16 10:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\.-]+@[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}$', message='Tienes que poner un email.')])),
                ('password', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\.-]+@[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}$', message='Tienes que poner un email.')])),
                ('password', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{8}[a-zA-Z]$', message='El DNI debe tener el formato 12345678X.')])),
                ('photo', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('firstSurname', models.CharField(max_length=255)),
                ('secondSurname', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9,15}$', message='El número de teléfono debe tener entre 9 y 15 dígitos.')])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dosis', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateFinish', models.DateTimeField(default=None)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\.-]+@[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}$', message='Tienes que poner un email.')])),
                ('password', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('firstSurname', models.CharField(max_length=255)),
                ('secondSurname', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9,15}$', message='El número de teléfono debe tener entre 9 y 15 dígitos.')])),
                ('healthCardCode', models.CharField(max_length=255, unique=True)),
                ('birthDate', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=1)),
                ('dni', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{8}[a-zA-Z]$', message='El DNI debe tener el formato 12345678X.')])),
                ('address', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSupport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('firstSurname', models.CharField(max_length=255)),
                ('secondSurname', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9,15}$', message='El número de teléfono debe tener entre 9 y 15 dígitos.')])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('morning_dose', models.DecimalField(choices=[(1, '1'), (0.5, '0.5'), (0, '0')], decimal_places=1, max_digits=2)),
                ('noon_dose', models.DecimalField(choices=[(1, '1'), (0.5, '0.5'), (0, '0')], decimal_places=1, max_digits=2)),
                ('night_dose', models.DecimalField(choices=[(1, '1'), (0.5, '0.5'), (0, '0')], decimal_places=1, max_digits=2)),
                ('active', models.BooleanField(default=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.medicine')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reportName', models.CharField(default='Informe medico', max_length=255)),
                ('disease', models.CharField(default=None, max_length=255)),
                ('reportInfo', models.CharField(max_length=255)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.report'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user')),
            ],
        ),
    ]
