# Generated by Django 5.0.4 on 2024-04-25 20:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=12, unique=True)),
                ('photo', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('firstSurname', models.CharField(max_length=255)),
                ('secondSurname', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999999999999999999999999999999999999999999999)])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('firstSurname', models.CharField(max_length=255)),
                ('secondSurname', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999999999999999999999999999999999999999999999)])),
                ('healthCardCode', models.CharField(max_length=255, unique=True)),
                ('birthDate', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=1)),
                ('dni', models.CharField(max_length=12, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSupport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('firstSurname', models.CharField(max_length=255)),
                ('secondSurname', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999999999999999999999999999999999999999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reportInfo', models.CharField(max_length=255)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.doctor')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine', models.CharField(max_length=255)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.doctor')),
                ('reportId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.report')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.doctor')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user')),
            ],
        ),
    ]
