# Generated by Django 5.0.4 on 2024-04-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersupport',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
