# Generated by Django 5.0.4 on 2024-05-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_recipe_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
