# Generated by Django 5.0.4 on 2024-05-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipe_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='disease',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='reportName',
            field=models.CharField(default='Informe medico', max_length=255),
        ),
    ]
